# mkdocs.yml
site_name: QENS_to_csv_app Documentation

theme:
  name: "material"

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          members_order: source

markdown_extensions:
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.blocks.caption
- footnotes
- tables
- pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - QENS to csv App: index.md
  - Tutorial: tutorials.md
  - how-to-guides.md
  - Ref. QENS to csv App: reference.md
  - Ref. FuncionesLeer: ref-funcionesleer.md
  - Explanation: explanation.md
